### ISSUE TITLE
Upload not working / Write-S3Object

### ISSUE THREAD

**Issue by mschindl** [NetApp-StorageGRID/S3-Client#3]
Any ideas why it isn't working?

![image](https://user-images.githubusercontent.com/26382876/43584885-f4cf0a34-9663-11e8-9577-55ff1a1fd21b.png)
![image](https://user-images.githubusercontent.com/26382876/43585797-4587aa92-9666-11e8-9137-95140fe1555f.png)
![image](https://user-images.githubusercontent.com/26382876/43585050-6c698024-9664-11e8-8628-542b3fc95a40.png)
![image](https://user-images.githubusercontent.com/26382876/43584894-f7f1de80-9663-11e8-9a38-d04eddfb6612.png)

**Comment by mschindl** [comment]
Issue solved after upgrade.

Example:
> Write-S3Object -BucketName <bucketname> -InFile /<filename>.pdf

**Comment by ang6300** [comment]
I have similar problem, unable to upload any file using -infile parameter.  I have c:\sg-ps\test.txt
Either it said file cannot be found or file in use, depending how I specify the infile filepath.

I am at c:\sg-ps directory when I run write-s3object, there is a file test.txt on this directory.
If I specify -infile .\test.txt or -infile test.txt, with or without “ “, I got file does not exist. 

If I specify -infile “c:\sg-ps\test.txt” I got file used by another process but definitely there is no other process using this file
Get-FileHash : The process cannot access the file 'C:\sg-ps\test.txt' because it
is being used by another process.

I am using powershell 6.2.3 and s3-client 1.19.0

**Comment by ffeldhaus** [comment]
Sorry @ang6300 that it is not working for you. There are some known issues in old .NET / PowerShell versions with locking files and not freeing up the lock, therefore it would be helpful to get some information about your environment. Can you provide the output from `$PSVersionTable` and `Get-Module -Name S3-Client`? Then I'll have a look if I can recreate the issue.

**Comment by ffeldhaus** [comment]
I just tried this on Windows 10 with PowerShell 6.2.3 and it works fine for me:
```powershell
PS C:\temp> "Hello World!" | Out-File -FilePath C:\temp\test.txt
PS C:\temp> New-S3Bucket -BucketName florianf-test-2020-01-02^C
PS C:\temp> $BucketName = Get-Random
PS C:\temp> $BucketName
938810914
PS C:\temp> New-S3Bucket -BucketName $BucketName
PS C:\temp> Write-S3Object -BucketName $BucketName -InFile C:\temp\test.txt

Uploading file test.txt of size 0 MiB to 938810914/x-amz-date completed in 0.57 seconds with average throughput of 0 MiB/s
ETag
----
7012acbb1d394b20567dffbf0992b677
```
